// <auto-generated />
using System;
using BinhDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BinhDemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240321022657_AddFirst")]
    partial class AddFirst
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BinhDemo.Models.Admin.Manages.Danhmuc.LoHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ChiPhiTk")
                        .HasColumnType("float");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuDieuKienThanhKhoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiaHanLan1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiaHanLan2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiaiPhongHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("KhoiLuongGiamDinh")
                        .HasColumnType("float");

                    b.Property<string>("KhuVuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiTk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBaoLanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayDangKiToKhai")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayDeNghiTk")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayGiaHanLan1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayGiaHanLan2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayQuyetDinhTk")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayVanDon")
                        .HasColumnType("datetime2");

                    b.Property<double?>("PhanChiaTxMienBac")
                        .HasColumnType("float");

                    b.Property<double?>("PhanChiaTxMienNam")
                        .HasColumnType("float");

                    b.Property<double?>("PhanChiaTxMienTrung")
                        .HasColumnType("float");

                    b.Property<string>("SoBaoLanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoLo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoToKhai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiHanNopThueDuocBl")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiHanTaiXuat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThongQuan")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LoHang");
                });

            modelBuilder.Entity("BinhDemo.Models.Admin.Systems.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CapDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("ChucDanhNguoiKyBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ChucNangKhac")
                        .HasColumnType("bit");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountLogin")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaDanhBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HeThong")
                        .HasColumnType("bit");

                    b.Property<string>("HoTenNguoiKyBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<string>("MaDonVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDvBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaHuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhomChucNang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaXa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Menu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NhapLieu")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanLoaiTk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Public")
                        .HasColumnType("int");

                    b.Property<string>("Remember_Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sadmin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDonViBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDonViChuQuanBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Theme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TongHop")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
